### ISSUE TITLE
Test with current version

### ISSUE THREAD

**Issue by GaborFarkas** [DateliteLtd/UserSpice5OnPostgres#1]
Please test the PostgreSQL integration with the current version of UserSpice, and fix inconsistencies coming from the updated base version, if any.

Please use PRs from pushed feature branches from now on.

**Comment by ssobii2** [comment]
So the one I did is not working?

**Comment by ssobii2** [comment]
So professor, for the pull request, I should make a separate branch just like previously, and then after pushing changes, I should create a pull request. Am I right?

**Comment by GaborFarkas** [comment]
I don't know if it's working or not with the current version of US, that's the reason behind this issue. Yes, you should create a PR from a pushed feature branch.

**Comment by ssobii2** [comment]
So should I upload only the userspice admin folder or the whole project like previously with a separate branch?

**Comment by ssobii2** [comment]
How did you merge my commits with another repository I didn't touch? Also, you forked this repo from someone. Was he working on this too?

**Comment by ssobii2** [comment]
Hi Professor, I am testing it so far, and only the login is working. I think you upgraded it to the new version, so the admin dashboard is crashing due to some new files and tables. I checked the apache logs because the error was 500. Some new Menu files are added with tables.

**Comment by GaborFarkas** [comment]
The repo is forked from the original UserSpice 5 repository. It is the newest version, so please do a fresh installation (with a new DB) after cloning this repository before testing it.

**Comment by ssobii2** [comment]
Update on the progress, professor.

1. It's working, but I need to test everything.
2. It's working with the old classic menu and not the new ultra menu. This is the major problem the page was not working.
3. It's working with the ultra menu, too, but only in the admin dashboard and pages you access from the dashboard. It's not working on the admin home page for some reason. Otherwise, it works everywhere. Would you like me to fix this? Will we use the ultra menu, or classic one is OK?
4. Also, when using the ultra menu on the admin home page, the page gives 500 internal error. I will check Apache logs for the issue, but I must first know whether we will use the ultra or old classic menu.
5. The template is not working. I don't remember our Bootstrap version, but it uses Bootstrap 5. Do you think I should update it? If yes, then how?

I am going to push to git the progress :)

**Comment by ssobii2** [comment]
Also by working I mean just going in the dashboard and accessing other pages, I haven't checked the services yet

**Comment by ssobii2** [comment]
Oh, I am not pushing to GitHub yet. Should I push with the whole project or just the contents of the admin folder?

**Comment by GaborFarkas** [comment]
Please do not confuse our other projects with this one. This repo is just a simple US5 on PostgreSQL, nothing more. Treat it like that. Everything must remain the same except the DB connection.

**Comment by ssobii2** [comment]
Ok professor I understand but what about my other questions about the menu and the template?

**Comment by GaborFarkas** [comment]
I'm afraid I don't understand your other questions. The menu system and the template must remain the same as the one used by UserSpice.

**Comment by ssobii2** [comment]
Ok i will explain in a sec with screenshots professor

**Comment by ssobii2** [comment]
![Image](https://user-images.githubusercontent.com/71027266/230108799-3f458c45-4f4d-4dbc-b5ed-5f7f75c785d8.png)

As you can see in this image there are 2 menus now. It works fine with the classic menu but there is an option to migrate to ultramenu which it recommends. But when I do that then the admin home page dosen't work, while dashboard works fine.

**Comment by ssobii2** [comment]
![Image](https://user-images.githubusercontent.com/71027266/230109334-e6ec14ae-8377-4a69-87bb-c63791b5f8be.png)

For the template part, you can see in the picture its not loading. So does this has something to do with bootstrap version? Because it supports 5.

**Comment by GaborFarkas** [comment]
Well, in this case, the best you can do is trying out the ultra menu with the original MySQL-backed US5. If the migration fails there as well, it is a US issue, and we won't fix it in this repo. If it works, this is a PostgreSQL incompatibility issue, which needs to be fixed.

**Comment by ssobii2** [comment]
I have fixed it somehow the admin home page is displaying but not the menu on the homepage. Menu works fine on the dashboard. I am trying to fix it.

**Comment by ssobii2** [comment]
Hi Professor, 
Update on the issue. So a migrate button in the classic menu option migrated the old menu to the ultra menu. So we have 2 main menus, one for the admin home page and one for the admin dashboard. The dashboard one migrated fine and is showing, but the home page one is on the ultra menu but not on the home page for some reason. I manually created one, and it showed right away, so I don't know the problem. Anyway, tomorrow, I will check it with the MYSQL db to see if it's the same. Otherwise, we can use the old one or manually create a new home page menu.
