### ISSUE TITLE
Compare with original MySQL version

### ISSUE THREAD

**Issue by GaborFarkas** [DateliteLtd/UserSpice5OnPostgres#7]
Please compare the PostgreSQL version with the MySQL version side by side. Trace and fix any inconsistencies. Make sure to check the DB as well after every insert/update.

**Comment by ssobii2** [comment]
Didn't we do this already, replacing the boolean with smallint? Should I check all of them again, including the update files?

**Comment by GaborFarkas** [comment]
All again, every feature, click by click.

**Comment by GaborFarkas** [comment]
Please don't rush, be very thorough instead.

**Comment by ssobii2** [comment]
> All again, every feature, click by click.

Oh, you mean the features the menu everything got it. Also now that my xdebug is working its showing errors in the new ultra menu when migrating. The classic menu works fine. What should I do to fix the ultra menu or stick with classic?

**Comment by GaborFarkas** [comment]
Fix every inconsistency. Check the MySQL version how it should work and fix the PostgreSQL one accordingly.

**Comment by GaborFarkas** [comment]
And of course start with a fresh installation.

**Comment by ssobii2** [comment]
> Please don't rush, be very thorough instead.

Yes professor I understand. The development will be slow as next week I have exams so I have to prepare for that too. I am right now working on the InSAR issue. Somehow after Windows update the xampp db is corrupt so I have to fix that now.

**Comment by ssobii2** [comment]
> And of course start with a fresh installation.

Ah yes after the mess I made sorry about that it was confusing. Any short course about git you recommend especially this rebase and revert stuff?

**Comment by ssobii2** [comment]
Hi Professor,

I am getting this error when adding a new item to the navigation menu
`ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type smallint: "" CONTEXT: unnamed portal parameter $10 = ''`
Here disabled column is of type smallint, which I changed from boolean, but idk why it still seems incompatible. The code checks for if the disabled checkbox is checked, and if not, it has an empty string like this `$item->disabled ? "checked" : ""`
Idk how it was working with MySQL, but here it is, passing an empty string instead of 0, leading to this error. Does tinyint support empty strings?
Anyway, I can fix this by forcing its default value to 0, and then it works. Oh, and if you check the disabled box without messing with the code just as it is, it works only it doesn't work If you keep it unchecked, which means 1 is passing correctly. I have a similar issue with the permission manager same invalid text representation error, but there it's for an integer and the same "" empty strings are being inserted. Another error when creating a new menu its inserting the "new" keyword in an integer column :(

Can it still be PostgreSQL incompatibility? if yes, then how should I fix it? If not, then should I mess with the PHP code to make everything work?

**Comment by ssobii2** [comment]
Also, as you said before, I fixed the code in DB.php, where I was using only the user's table sequence. Doing this fixed the menu migration from classic to ultra.

**Comment by GaborFarkas** [comment]
> Hi Professor,
> 
> I am getting this error when adding a new item to the navigation menu `ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type smallint: "" CONTEXT: unnamed portal parameter $10 = ''` Here disabled column is of type smallint, which I changed from boolean, but idk why it still seems incompatible. The code checks for if the disabled checkbox is checked, and if not, it has an empty string like this `$item->disabled ? "checked" : ""` Idk how it was working with MySQL, but here it is, passing an empty string instead of 0, leading to this error. Does tinyint support empty strings? Anyway, I can fix this by forcing its default value to 0, and then it works. Oh, and if you check the disabled box without messing with the code just as it is, it works only it doesn't work If you keep it unchecked, which means 1 is passing correctly. I have a similar issue with the permission manager same invalid text representation error, but there it's for an integer and the same "" empty strings are being inserted. Another error when creating a new menu its inserting the "new" keyword in an integer column :(
> 
> Can it still be PostgreSQL incompatibility? if yes, then how should I fix it? If not, then should I mess with the PHP code to make everything work?

Indeed, in these cases we must explicitly cast to 0 and 1 during form processing.

**Comment by ssobii2** [comment]
Hi Professor,
I haven’t made a pull request yet since i still to look at some services. I wanted to ask some services are working fine and some others are also working even though its showing a sql error. What should I do about these ones? I checked they are working fine even with the error displaying. I am asking because I can’t really pinpoint where the error is coming from. I have made commits if you want to check yourself though. Thanks

**Comment by ssobii2** [comment]
Hi Professor,
I haven’t made a pull request yet since i still to look at some services. I wanted to ask some services are working fine and some others are also working even though its showing a sql error. What should I do about these ones? I checked they are working fine even with the error displaying. I am asking because I can’t really pinpoint where the error is coming from. I have made commits if you want to check yourself though. Thanks

**Comment by GaborFarkas** [comment]
In these cases, please provide step-by-step guides to reproduce the errors and I will check into them when the PR arrives.

**Comment by ssobii2** [comment]
> In these cases, please provide step-by-step guides to reproduce the errors and I will check into them when the PR arrives.

Ok i will do a pull request after I am free from uni stuff today if possible

**Comment by GaborFarkas** [comment]
Please continue in the meantime, we will work together in parallel on the PR branch.

**Comment by ssobii2** [comment]
Ok, so far, I have checked everything except one thing, which is System logs. I will fix the issue, open a pull request, and let you know the errors with images that seem to be there but are not messing with anything.
